#!/usr/bin/env python3
"""
JIRA to Pydantic Model Generator

Analyzes pkg/helm Go code AST and generates relevant Pydantic models
based on JIRA issue acceptance criteria.

Usage:
    python jira_to_pydantic.py <ast_json_path> <jira_text_file> [output_file]

    Or provide JIRA text via stdin:
    echo "JIRA issue text..." | python jira_to_pydantic.py <ast_json_path> - [output_file]

    If output_file is not specified, prints to stdout.
"""

import json
import re
import sys
from typing import List, Dict, Set, Optional, Any
from dataclasses import dataclass
from collections import defaultdict


# ============================================================================
# Data Models
# ============================================================================

@dataclass
class StructRelevance:
    """Represents a Go struct with relevance scoring."""
    struct_name: str
    file_path: str
    fields: List[Dict]
    doc: str
    score: float
    reasons: List[str]


# ============================================================================
# Constants
# ============================================================================

STOP_WORDS = {
    "the", "a", "an", "and", "or", "but", "in", "on", "at", "to", "for",
    "of", "with", "by", "from", "as", "is", "was", "are", "were", "be",
    "been", "being", "have", "has", "had", "do", "does", "did", "will",
    "would", "should", "could", "may", "might", "must", "can", "this",
    "that", "these", "those", "i", "you", "he", "she", "it", "we", "they",
    "user", "able"
}


# ============================================================================
# Core Pipeline
# ============================================================================

def analyze_jira_and_generate_models(jira_text: str, ast_json_path: str):
    """
    Main pipeline: JIRA acceptance criteria → Relevant structs → Pydantic models

    Args:
        jira_text: JIRA issue description with acceptance criteria
        ast_json_path: Path to AST JSON generated by generate_helm_ast.go

    Returns:
        Tuple of (pydantic_models, scored_structs)
    """

    # Step 1: Load AST
    print(f"📖 Loading AST from {ast_json_path}...", file=sys.stderr)
    with open(ast_json_path) as f:
        ast_data = json.load(f)
    print(f"   Found {len(ast_data)} files in AST\n", file=sys.stderr)

    # Step 2: Extract intelligence from JIRA
    print("🔍 Analyzing JIRA text...", file=sys.stderr)
    intelligence = extract_jira_intelligence(jira_text)
    print(f"   Keywords: {', '.join(list(intelligence['keywords'])[:10])}", file=sys.stderr)
    print(f"   Action: {intelligence['action']}", file=sys.stderr)
    print(f"   Concepts: {', '.join(intelligence['concepts'])}", file=sys.stderr)
    print(f"   File hints: {', '.join(intelligence['file_hints'])}\n", file=sys.stderr)

    # Step 3: Score all structs
    print("⚖️  Scoring structs for relevance...", file=sys.stderr)
    scored_structs = []
    total_structs = 0

    for file_ast in ast_data:
        if file_ast.get("types"):
            for type_info in file_ast["types"]:
                total_structs += 1
                if type_info["kind"] == "struct":  # Only structs, not interfaces
                    score, reasons = calculate_relevance_score(
                        struct_name=type_info["name"],
                        fields=type_info.get("fields", []),
                        file_path=file_ast["path"],
                        doc=type_info.get("doc", ""),
                        intelligence=intelligence
                    )

                    if score > 0.5:  # Threshold
                        scored_structs.append(StructRelevance(
                            struct_name=type_info["name"],
                            file_path=file_ast["path"],
                            fields=type_info.get("fields", []),
                            doc=type_info.get("doc", ""),
                            score=score,
                            reasons=reasons
                        ))

    print(f"   Evaluated {total_structs} types", file=sys.stderr)
    print(f"   Found {len(scored_structs)} relevant structs (score > 0.5)\n", file=sys.stderr)

    # Step 4: Sort by relevance
    scored_structs.sort(key=lambda x: x.score, reverse=True)

    # Step 5: Generate Pydantic models for top N
    print("🔨 Generating Pydantic models...\n", file=sys.stderr)
    pydantic_models = []
    for struct in scored_structs[:10]:  # Top 10
        model = generate_pydantic_from_struct(struct)
        pydantic_models.append(model)

    return pydantic_models, scored_structs


# ============================================================================
# Intelligence Extraction
# ============================================================================

def extract_jira_intelligence(jira_text: str) -> Dict:
    """
    Extract structured intelligence from JIRA acceptance criteria.

    Returns dict with:
        - keywords: Set of technical keywords
        - action: Type of operation (create/update/delete/fix)
        - file_hints: Likely relevant files
        - concepts: Domain concepts detected
        - raw_text: Original JIRA text
    """
    text_lower = jira_text.lower()

    # Keywords extraction
    technical_keywords = set()
    for word in jira_text.split():
        cleaned = word.strip('.,!?:;()[]{}').lower()
        if len(cleaned) > 3 and cleaned not in STOP_WORDS:
            technical_keywords.add(cleaned)

    # Action detection (what operation is being done)
    action = "unknown"
    if any(word in text_lower for word in ["add", "create", "new"]):
        action = "create"
    elif any(word in text_lower for word in ["update", "modify", "change", "upgrade"]):
        action = "update"
    elif any(word in text_lower for word in ["delete", "remove"]):
        action = "delete"
    elif any(word in text_lower for word in ["fix", "bug"]):
        action = "fix"

    # File path hints
    file_hints = []
    if "upgrade" in text_lower:
        file_hints.append("upgrade_release.go")
    if "install" in text_lower:
        file_hints.append("install_chart.go")
    if "auth" in text_lower or "secret" in text_lower:
        file_hints.append("auth.go")
    if "chart" in text_lower:
        file_hints.extend(["get_chart.go", "utility.go"])
    if "rollback" in text_lower:
        file_hints.append("rollback_release.go")
    if "template" in text_lower:
        file_hints.append("template.go")

    # Domain concepts (specific to Helm)
    concepts = set()
    concept_map = {
        "helm": ["helm", "chart", "release"],
        "auth": ["auth", "authentication", "credentials", "secret", "password", "username"],
        "upgrade": ["upgrade", "update", "version"],
        "repository": ["repository", "repo", "registry"],
        "namespace": ["namespace", "project"],
        "install": ["install", "deployment"],
        "template": ["template", "render"],
    }

    for concept, keywords in concept_map.items():
        if any(kw in text_lower for kw in keywords):
            concepts.add(concept)

    return {
        "keywords": technical_keywords,
        "action": action,
        "file_hints": file_hints,
        "concepts": concepts,
        "raw_text": jira_text
    }


# ============================================================================
# Relevance Scoring
# ============================================================================

def calculate_relevance_score(
    struct_name: str,
    fields: List[Dict],
    file_path: str,
    doc: str,
    intelligence: Dict
) -> tuple[float, List[str]]:
    """
    Multi-signal scoring for struct relevance.

    Scoring weights:
        - Struct name matches keyword: 3.0
        - Field name matches keyword: 1.0 each (max 3)
        - File path matches hint: 4.0
        - Concept alignment: 2.0 (struct) or 1.0 (fields)
        - Documentation match: 0.5
        - Input/request pattern: 1.5
        - Generic name penalty: -1.0

    Returns:
        (score, reasons) tuple
    """
    score = 0.0
    reasons = []

    struct_lower = struct_name.lower()
    field_names = [f["name"].lower() for f in fields]
    field_types = [f["type"].lower() for f in fields]

    # Signal 1: Struct name matches keywords (HIGH WEIGHT: 3.0)
    for keyword in intelligence["keywords"]:
        if keyword in struct_lower:
            score += 3.0
            reasons.append(f"Struct name contains '{keyword}'")
            break  # Only count once

    # Signal 2: Field names match keywords (MEDIUM WEIGHT: 1.0 per match, max 3)
    field_matches = 0
    matched_keywords = set()
    for keyword in intelligence["keywords"]:
        for field_name in field_names:
            if keyword in field_name and keyword not in matched_keywords:
                field_matches += 1
                matched_keywords.add(keyword)
                if field_matches <= 3:
                    score += 1.0
                    reasons.append(f"Field matches keyword '{keyword}'")

    # Signal 3: File path matches hints (HIGH WEIGHT: 4.0)
    for hint in intelligence["file_hints"]:
        if hint in file_path:
            score += 4.0
            reasons.append(f"File path matches hint '{hint}'")
            break

    # Signal 4: Concept alignment (MEDIUM WEIGHT: 2.0)
    concept_indicators = {
        "auth": ["auth", "credential", "username", "password", "secret", "token"],
        "helm": ["chart", "release", "repository", "helm"],
        "upgrade": ["upgrade", "version", "update"],
        "repository": ["repository", "repo", "registry", "url"],
        "install": ["install", "deploy"],
        "namespace": ["namespace"],
    }

    for concept in intelligence["concepts"]:
        if concept in concept_indicators:
            indicators = concept_indicators[concept]
            if any(ind in struct_lower for ind in indicators):
                score += 2.0
                reasons.append(f"Struct aligns with concept '{concept}'")
            # Also check fields
            elif any(ind in " ".join(field_names) for ind in indicators):
                score += 1.0
                reasons.append(f"Fields align with concept '{concept}'")

    # Signal 5: Documentation match (LOW WEIGHT: 0.5)
    if doc:
        doc_lower = doc.lower()
        for keyword in intelligence["keywords"]:
            if keyword in doc_lower:
                score += 0.5
                reasons.append(f"Documentation mentions '{keyword}'")
                break

    # Signal 6: Action-specific patterns
    if intelligence["action"] == "create":
        # Look for "Request" or "Input" structs
        if "request" in struct_lower or "input" in struct_lower or "param" in struct_lower:
            score += 1.5
            reasons.append("Struct appears to be an input/request type")

    # Signal 7: Penalize overly generic names
    generic_names = ["config", "option", "settings"]
    if struct_lower in generic_names and score < 3.0:
        score -= 1.0
        reasons.append("Penalized for generic name")

    return score, reasons


# ============================================================================
# Pydantic Generation
# ============================================================================

def generate_pydantic_from_struct(struct: StructRelevance) -> str:
    """
    Generate Pydantic model code from Go struct.

    Maps Go types to Python types and handles optionality based on
    JSON tags and pointer types.
    """
    lines = []
    lines.append(f"class {struct.struct_name}(BaseModel):")
    lines.append(f'    """')
    lines.append(f'    Generated from {struct.file_path}')
    if struct.doc:
        lines.append(f'    ')
        lines.append(f'    {struct.doc.strip()}')
    lines.append(f'    ')
    lines.append(f'    Relevance Score: {struct.score:.2f}')
    lines.append(f'    Reasons: {", ".join(struct.reasons[:3])}')
    lines.append(f'    """')
    lines.append("")

    if not struct.fields:
        lines.append("    pass")
        return "\n".join(lines)

    for field in struct.fields:
        # Handle embedded fields (no name)
        if not field["name"]:
            continue

        field_name = to_snake_case(field["name"])
        go_type = field["type"]

        # Check for JSON tag to determine optionality
        tag = field.get("tag", "")
        is_optional = "omitempty" in tag or go_type.startswith("*")

        # Convert type
        field_type = go_type_to_python(go_type.lstrip("*"))

        # Generate field line
        if is_optional:
            lines.append(f"    {field_name}: Optional[{field_type}] = None")
        else:
            lines.append(f"    {field_name}: {field_type}")

    return "\n".join(lines)


def go_type_to_python(go_type: str) -> str:
    """Map Go types to Python/Pydantic types."""

    # Basic types
    type_map = {
        "string": "str",
        "bool": "bool",
        "int": "int",
        "int32": "int",
        "int64": "int",
        "uint": "int",
        "uint32": "int",
        "uint64": "int",
        "float32": "float",
        "float64": "float",
        "interface{}": "Any",
        "error": "str",  # Go error type
    }

    if go_type in type_map:
        return type_map[go_type]

    # Arrays/Slices
    if go_type.startswith("[]"):
        inner_type = go_type[2:]
        inner_python = go_type_to_python(inner_type)
        return f"list[{inner_python}]"

    # Maps
    if go_type.startswith("map["):
        match = re.match(r"map\[(.*?)\](.*)", go_type)
        if match:
            key_type = go_type_to_python(match.group(1))
            val_type = go_type_to_python(match.group(2))
            return f"dict[{key_type}, {val_type}]"

    # Complex types - might be nested structs, keep as string for now
    # In a real implementation, you'd generate nested models
    return f'"{go_type}"'  # Quote complex types


def to_snake_case(name: str) -> str:
    """Convert PascalCase/camelCase to snake_case."""
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()


# ============================================================================
# Output Formatting
# ============================================================================

def print_results(pydantic_models: List[str], scored_structs: List[StructRelevance]):
    """Pretty print the results."""

    print("=" * 80)
    print("TOP 10 MOST RELEVANT STRUCTS")
    print("=" * 80)
    print()

    for i, struct in enumerate(scored_structs[:10], 1):
        print(f"{i}. {struct.struct_name} (score: {struct.score:.2f})")
        print(f"   📁 File: {struct.file_path}")
        print(f"   💡 Reasons: {', '.join(struct.reasons[:3])}")
        if len(struct.reasons) > 3:
            print(f"              ... and {len(struct.reasons) - 3} more")
        print()

    print()
    print("=" * 80)
    print("GENERATED PYDANTIC MODELS")
    print("=" * 80)
    print()
    print("from pydantic import BaseModel")
    print("from typing import Optional, Any")
    print()
    print()

    for model in pydantic_models:
        print(model)
        print()
        print()


# ============================================================================
# CLI Interface
# ============================================================================

def main():
    """Main CLI entry point."""

    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)

    ast_json_path = sys.argv[1]
    jira_input = sys.argv[2]
    output_file = sys.argv[3] if len(sys.argv) > 3 else None

    # Read JIRA text
    if jira_input == "-":
        print("📥 Reading JIRA text from stdin...", file=sys.stderr)
        jira_text = sys.stdin.read()
    else:
        print(f"📥 Reading JIRA text from {jira_input}...", file=sys.stderr)
        with open(jira_input) as f:
            jira_text = f.read()

    print(file=sys.stderr)

    # Run analysis
    try:
        models, scored = analyze_jira_and_generate_models(jira_text, ast_json_path)

        # Determine output destination
        if output_file:
            print(f"💾 Writing output to {output_file}...", file=sys.stderr)
            with open(output_file, 'w') as f:
                # Redirect stdout to file
                original_stdout = sys.stdout
                sys.stdout = f
                print_results(models, scored)
                sys.stdout = original_stdout
            print(f"✅ Done! Output saved to {output_file}", file=sys.stderr)
        else:
            print_results(models, scored)

    except FileNotFoundError as e:
        print(f"❌ Error: {e}", file=sys.stderr)
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"❌ Error parsing AST JSON: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
